### ISSUE TITLE
How can I change the code to work with ResNet50?

### ISSUE THREAD

**Issue by monajalal** [christiansafka/img2vec#8]
I added these lines:

```
        elif model_name == 'resnet-50':
            model = models.resnet50(pretrained=True)
            if layer == 'default':
                layer = model._modules.get('avgpool')
                self.layer_output_size = 512
            else:
                layer = model._modules.get(layer)

```

But I get the following error:
```
[jalal@goku example]$ python img_to_vec_nearest_neighbors.py 
/scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Traceback (most recent call last):
  File "img_to_vec_nearest_neighbors.py", line 11, in <module>
    img2vec = Img2Vec()
  File "../img_to_vec.py", line 18, in __init__
    self.model, self.extraction_layer = self._get_model_and_layer(model, layer)
TypeError: 'NoneType' object is not iterable

```

**Comment by lianfenghua** [comment]
Maybe the line `return model, layer` should be added : )
```
            elif model_name == 'resnet-50':
            model = models.resnet50(pretrained=True)
            if layer == 'default':
                layer = model._modules.get('avgpool')
                self.layer_output_size = 512
            else:
                layer = model._modules.get(layer)
            return model, layer
```

**Comment by lianfenghua** [comment]
Maybe the line `return model, layer` should be added : )
```
        elif model_name == 'resnet-50':
            model = models.resnet50(pretrained=True)
            if layer == 'default':
                layer = model._modules.get('avgpool')
                self.layer_output_size = 512
            else:
                layer = model._modules.get(layer)
            return model, layer
```

**Comment by lianfenghua** [comment]
Maybe the line `return model, layer` should be added : )
```
        elif model_name == 'resnet-50':
            model = models.resnet50(pretrained=True)
            if layer == 'default':
                layer = model._modules.get('avgpool')
                self.layer_output_size = 512
            else:
                layer = model._modules.get(layer)
            return model, layer
```

**Comment by lianfenghua** [comment]
Maybe the line `return model, layer` should be added : )
```
        elif model_name == 'resnet-50':
            model = models.resnet50(pretrained=True)
            if layer == 'default':
                layer = model._modules.get('avgpool')
                self.layer_output_size = 512
            else:
                layer = model._modules.get(layer)
            return model, layer
```

**Comment by lianfenghua** [comment]
Maybe the line `return model, layer` should be added : )
```
        elif model_name == 'resnet-50':
            model = models.resnet50(pretrained=True)
            if layer == 'default':
                layer = model._modules.get('avgpool')
                self.layer_output_size = 512
            else:
                layer = model._modules.get(layer)
            return model, layer
```

**Comment by techietrader** [comment]
@monajalal  Did the solution work that @lianfenghua  gave?

If you check this link - http://ethereon.github.io/netscope/#/gist/db945b393d40bfa26006
The thrid last layer is the pooling layer , if you hover your mouse onto it, you will see it has 2048 activations.
So self.layer_output_size should be 2048.
I m not sure
Can you help
